# -*- coding: utf-8 -*-
"""frame_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ta3qVzqQ2AddlZHz0uVFF_x5XEuzJFn2
"""

import os
import uuid

file1 = open('/content/drive/MyDrive/image extraction/4_250-300.txt', 'r')
count = 0

path = "/content/drive/MyDrive/4_250-300/"



while True:

    count += 1

    random = str(uuid.uuid4())

    line = file1.readline()

    if not line:
        break

    print(path, random)
    os.mkdir(random)

    cmd = "ffmpeg -i {} -vf fps=20 -qscale 2 /content/drive/MyDrive/4_250-300/{}_%d.jpg".format(line.strip(),random,random)
    print(cmd)
    os.system(cmd)
 
file1.close()

from google.colab import drive
drive.mount('/content/drive')









